import type { Metadata } from "next";
import Link from "next/link";
import { JsonLd } from "@/components/site";
import { siteContent } from "@/lib/content";

export const metadata: Metadata = { title: "Search Fate Trigger Guide", description: "Search Fate Trigger guides, release updates, database records, media, and comparisons.", robots: { index: false, follow: true } };

export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams; const query = q.trim().toLowerCase();
  const content = siteContent as typeof siteContent & { guides: Array<{ slug: string; title: string; excerpt: string; keywords?: string[] }>; news: Array<{ slug: string; title: string; excerpt: string; tags?: string[] }>; entries: Array<{ slug: string; title: string; excerpt: string; category: string; tags?: string[] }>; videos: Array<{ slug: string; title: string; excerpt: string }>; comparisons: Array<{ slug: string; title: string; excerpt: string }> };
  const items = [...content.guides.map((item) => ({ title: item.title, description: item.excerpt, href: `/guides/${item.slug}`, type: "Guide", text: [item.title, item.excerpt, ...(item.keywords ?? [])].join(" ") })), ...content.news.map((item) => ({ title: item.title, description: item.excerpt, href: `/news/${item.slug}`, type: "News", text: [item.title, item.excerpt, ...(item.tags ?? [])].join(" ") })), ...content.entries.map((item) => ({ title: item.title, description: item.excerpt, href: `/database/${item.category}/${item.slug}`, type: "Database", text: [item.title, item.excerpt, item.category, ...(item.tags ?? [])].join(" ") })), ...content.videos.map((item) => ({ title: item.title, description: item.excerpt, href: `/media/${item.slug}`, type: "Media", text: `${item.title} ${item.excerpt}` })), ...content.comparisons.map((item) => ({ title: item.title, description: item.excerpt, href: `/comparisons/${item.slug}`, type: "Comparison", text: `${item.title} ${item.excerpt}` }))];
  const score = (item: typeof items[number]) => !query ? 0 : item.title.toLowerCase() === query ? 4 : item.title.toLowerCase().startsWith(query) ? 3 : item.type.toLowerCase().includes(query) ? 2 : 1;
  const results = items.filter((item) => !query || item.text.toLowerCase().includes(query)).filter((item, index, all) => all.findIndex((candidate) => candidate.href === item.href) === index).sort((a, b) => score(b) - score(a) || a.title.localeCompare(b.title)).slice(0, 30);
  const url = `https://${siteContent.domain}`;
  return <main className="section"><JsonLd data={{ "@context": "https://schema.org", "@type": "WebSite", name: siteContent.siteName, url, potentialAction: { "@type": "SearchAction", target: `${url}/search?q={search_term_string}`, "query-input": "required name=search_term_string" } }} /><p className="eyebrow">Guide search</p><h1>Search Fate Trigger guides and data</h1><p className="section-copy">Find release updates, roles, weapons, maps, media, and source-linked planning pages.</p><form action="/search" className="search-controls"><label>Search pages<input name="q" defaultValue={q} placeholder="Try weapons, Awakeners, maps, or release date" /></label><button className="button" type="submit">Search</button></form><p>{query ? `${results.length} result${results.length === 1 ? "" : "s"} for “${q}”` : `Browse ${Math.min(items.length, 30)} featured pages or enter a question.`}</p><div className="grid-3">{results.map((item) => <article className="card" key={item.href}><p className="eyebrow">{item.type}</p><h2><Link href={item.href}>{item.title}</Link></h2><p>{item.description}</p><Link href={item.href}>Open page</Link></article>)}</div></main>;
}
